defaults: cfgs/runai/dino/defaults.yaml

# Model
arch: convnext_small
drop_path_rate: 0.1
ssl_in_dim: 768
teacher_temp: 0.07
momentum_teacher: 0.9995
freeze_last_layer: 3
use_timm: False

# Optimizer & LR scheme
# default total batch size: 32*32=1024, 0.00075 lr, 2e-6 min_lr, 400 epochs
optimizer: adamw
lr: 5e-4
# lr: 2.5e-4
min_lr: 1e-5
clip_grad: 0.3
batch_size: 128
target_batch_size: 256

# Multi-crop parameters
global_crops_scale: [0.25, 1.0]
local_crops_scale: [0.05, 0.25]
local_crops_number: 10


# Logging
run_name: dino_convnext_small_imagenet_full