defaults: cfgs/runai/dino/defaults.yaml

# Model
arch: vit_small_patch16_224
ssl_in_dim: 384
dynamic_img_size: True
drop_path_rate: 0.1
patch_size: 16
use_timm: True
norm_last_layer: False
teacher_temp: 0.07
momentum_teacher: 0.9995


# norm_last_layer: False

# Optimizer & LR scheme
# default total batch size: 64*16=1024, 0.0005 lr, 1e-5 min_lr, 800 epochs
optimizer: adamw
batch_size: 128
target_batch_size: 256
lr: 5e-4
# lr: 2.5e-4
clip_grad: 0

# Multi-crop parameters
global_crops_scale: [0.25, 1.0]
local_crops_scale: [0.05, 0.25]
local_crops_number: 10

# Logging
run_name: dino_vit_small_imagenet_full