defaults: cfgs/runai/simclr/defaults.yaml

# Model
arch: vit_base_patch16_224
ssl_in_dim: 768
drop_path_rate: 0.1
patch_size: 16
use_timm: True


# norm_last_layer: False

# Optimizer & LR scheme
# default total batch size: 64*16=1024, 0.0005 lr, 1e-5 min_lr, 800 epochs
# optimizer: adamw
batch_size: 256
target_batch_size: 512
opt: adamw
lr: 1e-4
weight_decay: 0.05
clip_grad: 0

# Logging
run_name: simclr_vit_base_imagenet_full