experiment_name: ssl_scaling

data_filters:
    set_filters:
        dataset:
            - imagenet
            - ecoset

    boolean_filters:
        equals_true:
            - is_ssl
        equals_false:
            - is_pretrained
            - is_random
            - is_adv
            - is_ablation

    combine_arch_families: True

fitting_parameters:
    curve_type: 'one_variable'
    X: total_flops
    Y: score
    delta: 1e-3
    method: 'BFGS' # 'BFGS' or 'L-BFGS-B'
    use_log: True
    X_scaler: 1e13
    loss_function: power_law_LSE
    num_bootstraps: 1000
    data_fraction: 1
    random_seed: 42
    initial_parameters:
        e: [-1, -0.5, 0, 0.5, 1]
        a: [0, 5, 10, 15, 20, 25]
        alpha: [0, 0.5, 1, 1.5, 2]

visualization:
    loss_function: power_law

experiment_description: >
    ""