experiment_name: region_v2_group2
base_config: v2_base.yaml

data_filters:
    set_filters:
        arch_family:
            - ConvNeXt
            - ViT

fitting_parameters:
    loss_function: power_law_shift_LSE
    initial_parameters:
        lambda_: [0, 0.5, 1, 1.5, 2]

visualization:
    loss_function: power_law_shift

experiment_description: >
    ""