experiment_name: region_behavior_group1
base_config: behavior_base.yaml

data_filters:
    set_filters:
        arch_family:
            - ResNet
            - EfficientNet
            - CORnet-S
            - AlexNet

experiment_description: >
    ""