experiment_name: region_it_group1
base_config: it_base.yaml

data_filters:
    set_filters:
        arch_family:
            - ResNet
            - EfficientNet
            - CORnet-S
            - AlexNet

experiment_description: >
    ""