experiment_name: avg_scaling
base_config: ../region_base.yaml

data_filters:
    set_filters:
        region:
            - V1
            - V2
            - V4
            - IT
            - Behavioral


experiment_description: >
    ""