experiment_name: region_v4_group1
base_config: v4_base.yaml

data_filters:
    set_filters:
        arch_family:
            - ResNet
            - EfficientNet
            - CORnet-S
            - AlexNet

experiment_description: >
    ""