experiment_name: compute_behavior
base_config: compute_base.yaml

data_filters:
    set_filters:
        region:
            - Behavioral

# fitting_parameters:
#     loss_function: power_law_shift_LSE
#     initial_parameters:
#         lambda_: [0, 0.5, 1, 1.5, 2]

# visualization:
#     loss_function: power_law_shift



experiment_description: >
    ""