defaults: cfgs/runai/efficientnet/defaults.yaml

# Model
arch: efficientnet_v2_l

# Data
batch_size: 128

# Resizing
val_resize_size: 384
val_crop_size: 384
train_crop_size: 300
interpolation: 'bicubic'

# Logging
run_name: efficientnet_v2_l_test
# run_name: efficientnet_v2_l_imagenet_full