experiment_name: model_vit_avg
base_config: vit_base.yaml

data_filters:
    set_filters:
        region:
            - V1
            - V2
            - V4
            - IT
            - Behavioral

experiment_description: >
    ""