experiment_name: model_efficientnet_neuro
base_config: efficientnet_base.yaml

data_filters:
    set_filters:
        region:
            - V1
            - V2
            - V4
            - IT

experiment_description: >
    ""